[package]
name = "logger"
version = "0.1.0"
authors = ["dyike <yuanfeng634@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { version = "0.4.6", features = ["std"] }
time = "0.1.42"
